# manifest:
# remotes:
# - name: zmkfirmware
# url-base: https://github.com/zmkfirmware
# projects:
# - name: zmk
# remote: zmkfirmware
# revision: main
# import: app/west.yml
# self:
# path: config

manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: infused-kim
      url-base: https://github.com/infused-kim
  projects:
    - name: zmk
      remote: infused-kim
      revision: sofle
      import: app/west.yml
  self:
    path: config
# manifest:
# remotes:
# - name: petejohanson
# url-base: https://github.com/petejohanson
# projects:
# - name: zmk
# remote: petejohanson
# revision: core/zephyr-3.4-update
# import: app/west.yml
# self:
# path: config
