manifest:
  remotes:
    # - name: zmkfirmware
    # url-base: https://github.com/zmkfirmware
    # - name: urob
    # url-base: https://github.com/urob
    - name: petejohanson
      url-base: https://github.com/petejohanson
  projects:
    - name: zmk
      #remote: urob
      # remote: zmkfirmware
      remote: petejohanson
      revision: core/zephyr-3.4-update
      import: app/west.yml
  self:
    path: config
